/* RC645 — readable import panels and authoring readiness views. */

function buildReadableImportDiagnostics(runtime,text=runtime.contentStore.importDraft){
      const report=buildKitDiagnosticReport(runtime,text),plan=String(text||'').trim()?runtime.contentStore.previewImport(text,{collisionPolicy:runtime.contentStore.importCollisionPolicy}):null;const map=i=>({label:i.message,detail:i.impact||'',repair:i.correction,path:i.path,source:i.code,severity:i.severity});const blockers=report.items.filter(i=>i.severity==='blocker').map(map),warnings=report.items.filter(i=>i.severity==='warning').map(map),advice=report.items.filter(i=>i.severity==='advice').map(map);return {schema:'learnit.rc612.readable_import_diagnostics.v2',ok:report.ok,empty:!String(text||'').trim(),summary:report.summary,nextAction:report.nextAction,counters:{blockers:blockers.length,warnings:warnings.length,advice:advice.length,changes:plan&&plan.operations?plan.operations.length:0},blockers,warnings,advice,autoAccepted:(plan&&plan.rows||[]).filter(r=>r.action==='rename'||r.action==='skip'||r.action==='replace').map(r=>({label:`${r.title||r.courseId} · ${r.action}`,detail:`Politique ${plan.collisionPolicy}`,repair:'',path:r.path,source:'collision'})),raw:{diagnostics:report,plan}};
    }

function buildReadableImportDiagnosticsPanel(runtime,text=runtime.contentStore.importDraft){
      const d=buildReadableImportDiagnostics(runtime,text);if(d.empty)return `<div class="import-readable-panel"><div class="import-readable-head"><div><h3>Diagnostic du kit</h3><p>Choisissez un ou plusieurs fichiers JSON, ou collez un package.</p></div><span class="badge">EN ATTENTE</span></div></div>`;const badge=d.ok?'PRÊT':'BLOQUÉ',cls=d.ok?'ok':'warn';const row=(i,kind)=>`<div class="import-readable-item ${kind}"><strong>${escapeHtml(i.label)}</strong>${i.detail?`<span>${escapeHtml(i.detail)}</span>`:''}${i.repair?`<em>${escapeHtml(i.repair)}</em>`:''}${i.path?`<code>${escapeHtml(i.path)}</code>`:''}</div>`;const important=[...d.blockers,...d.warnings].slice(0,5).map(i=>row(i,i.severity||'warning')).join('');const details=[...d.blockers,...d.warnings,...d.advice].map(i=>row(i,i.severity||'advice')).join('');return `<div class="import-readable-panel"><div class="import-readable-head"><div><h3>Diagnostic du kit</h3><p>${escapeHtml(d.summary)} · ${escapeHtml(d.nextAction)}</p></div><span class="badge ${cls}">${badge}</span></div><div class="import-readable-grid"><div class="import-stat"><b>${d.counters.blockers}</b><span>blocages</span></div><div class="import-stat"><b>${d.counters.warnings}</b><span>avertissements</span></div><div class="import-stat"><b>${d.counters.advice}</b><span>conseils</span></div><div class="import-stat"><b>${d.counters.changes}</b><span>changements</span></div></div>${important||'<p class="tiny">Aucun problème prioritaire.</p>'}<details class="import-diagnostic-details"><summary>Voir tous les diagnostics</summary><div class="import-readable-columns">${details||'<p class="tiny">Aucun diagnostic.</p>'}</div></details></div>`;
    }

function buildAppliedImportPanel(runtime){
      const report=runtime.contentStore.lastAppliedImportReport();
      if(!report)return `<div class="import-preview applied-import-panel"><div class="import-preview-head"><div><div class="import-preview-title">Dernier import appliqué</div><div class="import-preview-sub">Aucun import appliqué dans cette session de stockage.</div></div><span class="badge">en attente</span></div></div>`;
      const rows=Array.isArray(report.rows)?report.rows:[];
      const stats=`<div class="import-preview-grid"><div class="import-stat"><b>${rows.length}</b><span>parcours ajoutés</span></div><div class="import-stat"><b>${Number(report.totalActivities||0)}</b><span>activités</span></div><div class="import-stat"><b>${Number(report.autoRenamed||0)}</b><span>suffixé(s)</span></div><div class="import-stat"><b>${Number(report.importedTotal||0)}</b><span>importés au total</span></div></div>`;
      const list=rows.map(r=>`<div class="import-course-row ${r.autoRenamed?'warn':'ok'}"><strong>${escapeHtml(r.title||r.courseId)}</strong><div class="import-type-row"><span class="badge">${escapeHtml(r.courseId||'')}</span><span class="badge">${Number(r.activityCount||0)} activité(s)</span>${r.autoRenamed?`<span class="badge warn">suffixe ${escapeHtml(r.autoSuffix||'— copie')}</span>`:''}</div><div class="import-mini">Original : ${escapeHtml(r.originalTitle||r.title||'')} · package : ${escapeHtml(report.packageId||'')}</div></div>`).join('');
      return `<div class="import-preview applied-import-panel"><div class="import-preview-head"><div><div class="import-preview-title">Dernier import appliqué</div><div class="import-preview-sub">${escapeHtml(report.packageId||'package')} · ${escapeHtml(report.appliedAt||'date inconnue')} · preuve persistée durablement et exportable.</div></div><span class="badge ok">APPLIQUÉ</span></div>${stats}<div class="import-course-list">${list}</div><div class="actions"><button data-action="library-show-imported">Voir les parcours importés</button><button data-action="export-applied-import">Exporter rapport import appliqué</button></div></div>`;
    }

function buildImportPreviewPanel(runtime,text=runtime.contentStore.importDraft){
      const src=String(text||'');if(!src.trim())return `<div class="import-preview"><div class="import-preview-head"><div><div class="import-preview-title">Prévisualisation</div><div class="import-preview-sub">Aucune modification ne sera faite avant validation.</div></div><span class="badge">EN ATTENTE</span></div></div>`;const plan=runtime.contentStore.previewImport(src,{collisionPolicy:runtime.contentStore.importCollisionPolicy}),diag=buildKitDiagnosticReport(runtime,src),confirmed=runtime.contentStore.importPreviewConfirmed&&runtime.contentStore.importPreviewPlan&&runtime.contentStore.importPreviewPlan.digest===plan.digest;const status=!plan.ok||!diag.ok?'BLOQUÉ':confirmed?'CONFIRMÉ':'À CONFIRMER',cls=!plan.ok||!diag.ok?'warn':confirmed?'ok':'';const counts=plan.counts||{};const rows=(plan.rows||[]).map(r=>`<div class="import-course-row ${r.ok?'ok':'warn'}"><label class="import-title-editor"><span>Nom du parcours</span><input class="import-title-override" data-import-title-key="${escapeHtml(r.titleOverrideKey||'')}" value="${escapeHtml(r.requestedTitle||r.title||r.courseId)}" maxlength="120" autocomplete="off"></label><div class="import-type-row"><span class="badge">${escapeHtml(r.action)}</span><span class="badge">${Number(r.activityCount||0)} activité(s)</span><span class="badge">${escapeHtml(r.sourceName||'JSON')}</span></div><div class="import-mini">Identifiant stable : ${escapeHtml(r.courseId||'')} · nom source : ${escapeHtml(r.sourceTitle||r.originalTitle||'')}</div></div>`).join('');return `<div class="import-preview" data-import-plan-digest="${escapeHtml(plan.digest||'')}"><div class="import-preview-head"><div><div class="import-preview-title">Prévisualisation sans écriture</div><div class="import-preview-sub">Politique de collision : ${escapeHtml(plan.collisionPolicy)} · ${escapeHtml(plan.message||diag.summary)}</div></div><span class="badge ${cls}">${status}</span></div><div class="import-preview-grid"><div class="import-stat"><b>${plan.rows.length}</b><span>parcours analysés</span></div><div class="import-stat"><b>${plan.operations.length}</b><span>changements</span></div><div class="import-stat"><b>${counts.rename||0}</b><span>renommés</span></div><div class="import-stat"><b>${counts.replace||0}</b><span>remplacés</span></div><div class="import-stat"><b>${counts.skip||0}</b><span>ignorés</span></div><div class="import-stat"><b>${plan.totalActivities||0}</b><span>activités</span></div></div><div class="import-impact">Bibliothèque : ${plan.beforeImported} importé(s) avant → ${plan.afterImported} après. L’import est transactionnel : en cas d’échec, l’état précédent est restauré.</div><details class="import-plan-details" ${plan.rows.length<=4?'open':''}><summary>Voir le plan détaillé</summary><div class="import-course-list">${rows}</div></details></div>`;
    }

function buildAuthoringReadiness(runtime){
      const c=runtime.contentStore.content;
      const template={kind:'learnit-content-patch',patchId:'patch-'+runtime.contentStore.activeCourseId+'-example',courseId:runtime.contentStore.activeCourseId,sourceContentVersion:c.contentVersion,targetContentVersion:c.contentVersion+'-edited',reason:'Décrire le problème observé et l’amélioration attendue.',operations:[{op:'replaceActivityFields',id:c.activities[0].id,fields:{remediation:c.activities[0].remediation}}]};
      const checks=[
        {code:'template-versioned',ok:!!template.sourceContentVersion&&!!template.targetContentVersion,label:'Modèle de patch versionné'},
        {code:'course-scoped',ok:template.courseId===runtime.contentStore.activeCourseId,label:'Patch rattaché au parcours actif'},
        {code:'rollback-ready',ok:Array.isArray(runtime.contentStore.history),label:'Rollback disponible'},
        {code:'content-validation',ok:runtime.contentStore.validation.ok,label:'Contenu actif valide'},
        {code:'import-validator',ok:typeof runtime.contentStore.previewImport==='function',label:'Validateur import disponible'},
        {code:'import-rollback',ok:typeof runtime.contentStore.rollbackImport==='function',label:'Rollback import disponible'}
      ];
      return {ok:checks.every(c=>c.ok),template,checks};
    }

function rc193TitleCaseToken(token){
      const lower=String(token||'').toLowerCase();
      if(!lower)return '';
      if(['mi2','rc156','rc189'].includes(lower))return lower.toUpperCase();
      if(lower==='v11')return 'V11';
      return lower.charAt(0).toUpperCase()+lower.slice(1);
    }
