/* RC639 — pointer interaction fallback owner; order/matching dedicated modules remain authoritative. */
(function(){
  'use strict';
  Object.assign(AppRuntime.prototype,{
    syncOrderSelectionDom(token){
            this.root.querySelectorAll('.order-card.selected,[aria-selected="true"]').forEach(el=>{el.classList.remove('selected');el.setAttribute('aria-selected','false');});
            const card=this.root.querySelector(`[data-drag-order-token="${(window.CSS&&CSS.escape?CSS.escape(String(token||'')):String(token||'').replace(/[^a-zA-Z0-9_-]/g,'\\$&'))}"]`);
            if(card){card.classList.add('selected');card.setAttribute('aria-selected','true');}
            const values=Array.isArray(this.answer.pending)?this.answer.pending:[];
            const idx=values.indexOf(token);
            this.root.querySelectorAll('[data-action="order-move-selected"]').forEach(btn=>{
              const dir=Number(btn.dataset.dir||0);
              const disabled=idx<0 || idx+dir<0 || idx+dir>=values.length;
              btn.disabled=disabled;
              if(disabled)btn.setAttribute('disabled',''); else btn.removeAttribute('disabled');
            });
          },
    handlePointerDown(event){if(this.answer.feedback)return;const match=event.target.closest('[data-drag-match-right]');if(match){event.preventDefault();const dragData={type:'matching',right:match.dataset.dragMatchRight,label:match.textContent.trim()||match.dataset.dragMatchRight,source:match};if(window.LearnItMatchingActivity&&window.LearnItMatchingActivity.pointer&&typeof window.LearnItMatchingActivity.pointer.start==='function')window.LearnItMatchingActivity.pointer.start(this,event,dragData);else this.startDrag(event,dragData);return;}const order=event.target.closest('[data-drag-order-token]');if(order){event.preventDefault();const token=order.dataset.dragOrderToken;this.answer.ensureOrderPending('pointerdown');this.answer.selectedOrderToken=token;this.syncOrderSelectionDom(token);const dragData={type:'order',token,label:order.querySelector('.order-text')?.textContent?.trim()||token,source:order,overIndex:(Array.isArray(this.answer.pending)?this.answer.pending.indexOf(token):0)};if(window.LearnItOrderActivity&&window.LearnItOrderActivity.pointer&&typeof window.LearnItOrderActivity.pointer.start==='function')window.LearnItOrderActivity.pointer.start(this,event,dragData);else this.startDrag(event,dragData);return;}},
    startDrag(event,data){if(this.drag){this.journal.record('drag_orphan_recovered',{previousType:this.drag.type,newType:data.type});this.cleanupDrag(true);}const rect=data.source.getBoundingClientRect();const grabX=event.clientX-rect.left;const grabY=event.clientY-rect.top;this.drag={...data,pointerId:event.pointerId,startX:event.clientX,startY:event.clientY,x:event.clientX,y:event.clientY,moved:false,ghost:null,raf:0,lastDrop:null,sourceRect:{width:rect.width,height:rect.height},placeholderHeight:Math.ceil(rect.height),grabX,grabY,offsetX:0,offsetY:0,watchdog:0};try{data.source.setPointerCapture(event.pointerId);}catch(e){/* no-op */}this.drag.watchdog=setTimeout(()=>{if(this.drag&&this.drag.pointerId===event.pointerId){this.journal.record('drag_watchdog_cleanup',{type:this.drag.type,label:this.drag.label});this.cleanupDrag(true);}},9000);this.journal.record('direct_drag_start',{type:data.type,label:data.label});},
    handlePointerMove(event){const d=this.drag;if(!d||event.pointerId!==d.pointerId)return;if(d.type==='matching'&&window.LearnItMatchingActivity&&window.LearnItMatchingActivity.pointer&&typeof window.LearnItMatchingActivity.pointer.move==='function'){window.LearnItMatchingActivity.pointer.move(this,event);return;}if(d.type==='order'&&window.LearnItOrderActivity&&window.LearnItOrderActivity.pointer&&typeof window.LearnItOrderActivity.pointer.move==='function'){window.LearnItOrderActivity.pointer.move(this,event);return;}d.x=event.clientX;d.y=event.clientY;const dx=d.x-d.startX,dy=d.y-d.startY;if(!d.moved&&Math.hypot(dx,dy)<4)return;if(!d.moved){d.moved=true;this.suppressNextClick=true;if(d.type==='order'&&d.source)d.source.classList.add('drag-source');this.createDragGhost(d);if(d.type!=='order'&&d.source)d.source.classList.add('drag-source');document.body.classList.add('drag-active');}event.preventDefault();this.scheduleDragFrame();if(d.type==='matching')this.updateMatchingDrop(d);else if(d.type==='order')this.updateOrderPreview(d);},
    createDragGhost(d){const g=document.createElement('div');g.className=d.type==='order'?'drag-ghost order-card':'drag-ghost label-card';g.textContent=d.label;g.style.visibility='hidden';g.style.transition='none';g.style.animation='none';g.style.transform='translate3d(0,0,0)';const viewport=Math.max(180,window.innerWidth-36);const wanted=Math.min(Math.max(d.sourceRect.width,120),viewport);g.style.width=wanted+'px';document.body.appendChild(g);d.ghost=g;const rect=g.getBoundingClientRect();if(d.type==='matching'){d.offsetX=rect.width/2;d.offsetY=rect.height/2;}else{const sourceW=Math.max(1,d.sourceRect.width||rect.width);const sourceH=Math.max(1,d.sourceRect.height||rect.height);d.offsetX=Math.min(Math.max(d.grabX*(rect.width/sourceW),0),rect.width);d.offsetY=Math.min(Math.max(d.grabY*(rect.height/sourceH),0),rect.height);}this.positionDragGhostNow(d);g.getBoundingClientRect();g.style.visibility='visible';},
    positionDragGhostNow(d){if(!d||!d.ghost)return;const x=d.x-d.offsetX;const y=d.y-d.offsetY;d.ghost.style.transform=`translate3d(${x}px,${y}px,0)`;},
    scheduleDragFrame(){const d=this.drag;if(!d||d.raf)return;d.raf=requestAnimationFrame(()=>{d.raf=0;this.positionDragGhostNow(d);});},
    clearDropHints(){this.root.querySelectorAll('.hot').forEach(el=>el.classList.remove('hot'));},
    elementUnderDrag(d){if(d&&d.ghost)d.ghost.style.display='none';const el=document.elementFromPoint(d.x,d.y);if(d&&d.ghost)d.ghost.style.display='';return el;},
    updateMatchingDrop(d){this.clearDropHints();d.lastDrop=null;const el=this.elementUnderDrag(d);if(!el)return;const target=el.closest('[data-match-left]');if(target){target.classList.add('hot');const row=target.closest('.match-row');if(row)row.classList.add('hot');d.lastDrop={type:'matching',left:target.dataset.matchLeft,right:d.right};}},
    computeOrderIndex(y){const board=this.root.querySelector('.order-board');if(!board)return 0;const cards=Array.from(board.querySelectorAll('[data-drag-order-token]')).filter(card=>card.dataset.dragOrderToken!==this.drag?.token&&!card.classList.contains('drag-source'));for(let i=0;i<cards.length;i++){const rect=cards[i].getBoundingClientRect();if(y<rect.top+rect.height/2)return i;}return cards.length;},
    syncOrderPreviewDom(d){
            const board=this.root.querySelector('.order-board');if(!board)return;
            const placeholders=Array.from(board.querySelectorAll('[data-order-drag-placeholder="true"],.order-placeholder'));
            let ph=placeholders[0]||null;
            placeholders.slice(1).forEach(el=>el.remove());
            if(d.overIndex===null||d.overIndex===undefined){if(ph)ph.remove();return;}
            if(!ph){ph=document.createElement('div');ph.className='order-placeholder';ph.setAttribute('aria-hidden','true');}
            ph.dataset.orderDragPlaceholder='true';
            ph.className='order-placeholder';
            ph.style.setProperty('--order-placeholder-height',Math.max(48,Math.round(Number(d.placeholderHeight)||d.sourceRect?.height||66))+'px');
            const cards=Array.from(board.querySelectorAll('[data-drag-order-token]')).filter(card=>card.dataset.dragOrderToken!==d.token&&!card.classList.contains('drag-source'));
            const before=cards[Math.max(0,Math.min(Number(d.overIndex)||0,cards.length))]||null;
            if(before)board.insertBefore(ph,before);else board.appendChild(ph);
          },
    updateOrderPreview(d){const board=this.root.querySelector('.order-board');if(!board)return;const el=this.elementUnderDrag(d);const inside=!!(el&&el.closest&&el.closest('.order-board'));if(!inside){d.overIndex=null;d.lastDrop=null;this.syncOrderPreviewDom(d);return;}const next=this.computeOrderIndex(d.y);d.overIndex=next;d.lastDrop={type:'order',index:next};this.syncOrderPreviewDom(d);},
    handlePointerUp(event){const d=this.drag;if(!d||event.pointerId!==d.pointerId)return;if(d.type==='matching'&&window.LearnItMatchingActivity&&window.LearnItMatchingActivity.pointer&&typeof window.LearnItMatchingActivity.pointer.end==='function'){window.LearnItMatchingActivity.pointer.end(this,event);return;}if(d.type==='order'&&window.LearnItOrderActivity&&window.LearnItOrderActivity.pointer&&typeof window.LearnItOrderActivity.pointer.end==='function'){window.LearnItOrderActivity.pointer.end(this,event);return;}if(d.moved)event.preventDefault();const drop=d.lastDrop;const moved=d.moved;const token=d.token;this.cleanupDrag(true);if(moved&&drop&&drop.type==='matching')this.answer.dragMatch(drop.left,drop.right);if(moved&&token&&drop&&drop.type==='order')this.answer.moveOrderToIndex(token,drop.index);},
    handlePointerCancel(event){if(this.drag&&this.drag.type==='matching'&&window.LearnItMatchingActivity&&window.LearnItMatchingActivity.pointer&&typeof window.LearnItMatchingActivity.pointer.cancel==='function'){window.LearnItMatchingActivity.pointer.cancel(this,event);return;}if(this.drag&&this.drag.type==='order'&&window.LearnItOrderActivity&&window.LearnItOrderActivity.pointer&&typeof window.LearnItOrderActivity.pointer.cancel==='function'){window.LearnItOrderActivity.pointer.cancel(this,event);return;}if(this.drag&&event.pointerId===this.drag.pointerId)this.cleanupDrag(true);},
    cleanupDrag(skipRender=false){const d=this.drag;if(d&&d.type==='matching'&&window.LearnItMatchingActivity&&window.LearnItMatchingActivity.pointer&&typeof window.LearnItMatchingActivity.pointer.cleanup==='function'){window.LearnItMatchingActivity.pointer.cleanup(this,skipRender);return;}if(d&&d.type==='order'&&window.LearnItOrderActivity&&window.LearnItOrderActivity.pointer&&typeof window.LearnItOrderActivity.pointer.cleanup==='function'){window.LearnItOrderActivity.pointer.cleanup(this,skipRender);return;}if(d&&d.watchdog)clearTimeout(d.watchdog);if(d&&d.raf)cancelAnimationFrame(d.raf);if(d&&d.ghost)d.ghost.remove();if(d&&d.source){try{if(d.pointerId!==undefined&&d.source.hasPointerCapture&&d.source.hasPointerCapture(d.pointerId))d.source.releasePointerCapture(d.pointerId);}catch(e){/* no-op */}d.source.classList.remove('drag-source');}this.root.querySelectorAll('[data-order-drag-placeholder="true"],.order-placeholder').forEach(el=>el.remove());document.body.classList.remove('drag-active');this.clearDropHints();const needsRender=d&&d.type==='order'&&d.moved;this.drag=null;if(this.suppressNextClick)requestAnimationFrame(()=>{this.suppressNextClick=false;});if(needsRender&&!skipRender)this.render();}
  });
})();
