    function automationSleep(ms){return new Promise(resolve=>setTimeout(resolve,ms));}
    function automationFrame(){return new Promise(resolve=>requestAnimationFrame(()=>resolve()));}
    function automationSafeError(error){return String(error && (error.stack||error.message) || error);}
    function automationStepResult(label, ok, detail, data){return {label, ok:!!ok, detail:detail||'', data:data||null, at:new Date().toISOString()};}
    function automationGetRuntime(){const t=window.__LEARNIT_TEST__; if(!t||!t.runtime)throw new Error('Runtime test API unavailable'); return t.runtime;}
    function automationResetImported(runtime){
      runtime.contentStore.imported=[];
      runtime.contentStore.saveImportedCourses();
      runtime.contentStore.saveImportHistory([]);
      const base=(runtime.contentStore.courseList().find(c=>!c.imported)||runtime.contentStore.courseList()[0]);
      runtime.contentStore.setActiveCourse(base.courseId);
      runtime.appState.resetAll();
      runtime.appState.alignWithContent();
      runtime.answer.reset();
      runtime.render();
    }
    function automationAnswerCurrent(runtime, correct){
      const a=runtime.session.currentActivity();
      if(!a) throw new Error('No current activity');
      if(a.type==='qcm'){const expected=Number(a.answer||0);runtime.answer.pending=correct?expected:((expected+1)%Math.max(1,a.choices.length));}
      else if(a.type==='fill'){runtime.answer.pending=correct?[...a.answer]:a.answer.map((v,i)=>i===0?'__wrong__':v);}
      else if(a.type==='matching'){const matches={};a.pairs.forEach(([left,right],idx)=>{matches[left]=correct?right:a.pairs[(idx+1)%a.pairs.length][1];});runtime.answer.pending={matches,selectedRight:null};}
      else if(a.type==='order'){runtime.answer.pending=correct?[...a.answer]:[...a.answer].reverse();}
      else if(a.type==='flashcard'){runtime.answer.revealFlashcard(); runtime.answer.gradeFlashcard(!!correct); const got=!!runtime.answer.feedback.correct; return {id:a.id,type:a.type,expectedCorrect:!!correct,gotCorrect:got,ok:got===!!correct};}
      else throw new Error('Unsupported activity type '+a.type);
      runtime.answer.validate();
      const got=!!runtime.answer.feedback.correct;
      return {id:a.id,type:a.type,expectedCorrect:!!correct,gotCorrect:got,ok:got===!!correct};
    }
    function automationFirePointer(target,type,x,y,id){
      const ev=new PointerEvent(type,{bubbles:true,cancelable:true,clientX:x,clientY:y,pointerId:id||91,pointerType:'mouse',isPrimary:true,buttons:type==='pointerup'?0:1});
      target.dispatchEvent(ev);
    }
    async function automationSimulateDrag(runtime,kind){
      await automationFrame();
      let source,target;
      if(kind==='matching'){source=document.querySelector('[data-drag-match-right]');target=document.querySelector('[data-match-left]');}
      else {const cards=Array.from(document.querySelectorAll('[data-drag-order-token]'));source=cards[0];target=cards[cards.length-1]||cards[0];}
      if(!source||!target) throw new Error('Missing drag endpoints for '+kind);
      source.scrollIntoView({block:'center',inline:'center'}); await automationFrame();
      const sr=source.getBoundingClientRect(); const tr=target.getBoundingClientRect();
      const sx=sr.left+sr.width/2, sy=sr.top+sr.height/2;
      const tx=tr.left+tr.width/2, ty=kind==='order'?tr.bottom+Math.min(24,tr.height/2):tr.top+tr.height/2;
      const before=kind==='order'?JSON.stringify(runtime.answer.pending):JSON.stringify(runtime.answer.pending&&runtime.answer.pending.matches||{});
      automationFirePointer(source,'pointerdown',sx,sy,101);
      document.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,cancelable:true,clientX:(sx+tx)/2,clientY:(sy+ty)/2,pointerId:101,pointerType:'mouse',isPrimary:true,buttons:1}));
      await automationFrame();
      document.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,cancelable:true,clientX:tx,clientY:ty,pointerId:101,pointerType:'mouse',isPrimary:true,buttons:1}));
      await automationFrame();
      document.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,cancelable:true,clientX:tx,clientY:ty,pointerId:101,pointerType:'mouse',isPrimary:true,buttons:0}));
      await automationFrame();
      const after=kind==='order'?JSON.stringify(runtime.answer.pending):JSON.stringify(runtime.answer.pending&&runtime.answer.pending.matches||{});
      return {kind,before,after,changed:before!==after,ghostClean:!document.querySelector('.drag-ghost'),dragClassClean:!document.body.classList.contains('drag-active')};
    }
    async function automationRunGoldenPath(options){
      const started=new Date().toISOString(); const results=[]; let importedCourseId=null; let runtime=null;
      function push(label,ok,detail,data){results.push(automationStepResult(label,ok,detail,data));}
      async function runStep(label,fn){try{const value=await fn();const ok=(value&&typeof value==='object'&&'ok' in value)?value.ok:!!value;push(label,ok,value&&value.detail||'',value);return value;}catch(error){push(label,false,automationSafeError(error),null);return null;}}
      await runStep('runtime available',async()=>{runtime=automationGetRuntime();return {ok:!!runtime,version:window.__LEARNIT_TEST__.version};});
      await runStep('reset imported state',async()=>{automationResetImported(runtime);return {ok:runtime.contentStore.imported.length===0,detail:'imported='+runtime.contentStore.imported.length};});
      await runStep('surface route smoke',async()=>{const rows=window.__LEARNIT_TEST__.surfaceRouteSmoke();return {ok:rows.every(r=>r.ok),rows};});
      await runStep('import preview + contract + pedagogy diagnostics',async()=>{const text=JSON.stringify(AUTOMATION_TEST_KIT);runtime.contentStore.importDraft=text;const preview=runtime.contentStore.previewImport(text);const importDiag=window.__LEARNIT_TEST__.importDiagnostics(text);const contract=window.__LEARNIT_TEST__.contractDiagnostics(text);const pedagogy=window.__LEARNIT_TEST__.pedagogicalQuality(text);importedCourseId=preview&&preview.rows&&preview.rows[0]&&preview.rows[0].courseId;return {ok:!!(preview.ok&&importDiag.import?.ok!==false&&contract.ok&&pedagogy.ok),preview,contractSummary:contract.summary,pedagogySummary:pedagogy.summary,importedCourseId};});
      await runStep('apply import and select imported course',async()=>{runtime.contentStore.importPreviewConfirmed=true;const applied=runtime.contentStore.applyImportDraft(runtime.contentStore.importDraft);if(!applied.ok)return {ok:false,detail:applied.error,applied};runtime.contentStore.setActiveCourse(importedCourseId);runtime.appState.alignWithContent();runtime.answer.reset();runtime.go('library');await automationFrame();const active=runtime.contentStore.activeCourseId;return {ok:active===importedCourseId&&runtime.contentStore.content.activities.length>=4,active,activities:runtime.contentStore.content.activities.length,types:[...new Set(runtime.contentStore.content.activities.map(a=>a.type))]};});
      await runStep('matching pointer drag changes state',async()=>{const a=runtime.contentStore.content.activities.find(x=>x.type==='matching');runtime.session.startTargetedReview([a.id],{summary:'automation matching drag'});runtime.answer.reset();runtime.go('session');await automationFrame();const r=await automationSimulateDrag(runtime,'matching');return {ok:r.changed&&r.ghostClean&&r.dragClassClean,...r};});
      await runStep('order pointer drag changes state',async()=>{const a=runtime.contentStore.content.activities.find(x=>x.type==='order');runtime.session.startTargetedReview([a.id],{summary:'automation order drag'});runtime.answer.reset();runtime.go('session');await automationFrame();const r=await automationSimulateDrag(runtime,'order');return {ok:r.changed&&r.ghostClean&&r.dragClassClean,...r};});
      await runStep('flashcard active recall and media render',async()=>{const a=runtime.contentStore.content.activities.find(x=>x.type==='flashcard'&&Array.isArray(x.media)&&x.media.length);runtime.session.startTargetedReview([a.id],{summary:'automation flashcard media'});runtime.answer.reset();runtime.go('session');await automationFrame();const flash=!!document.querySelector('[data-activity-type="flashcard"]');const media=!!document.querySelector('.media-figure');runtime.answer.revealFlashcard();await automationFrame();const back=!!document.querySelector('.flashcard-face.back');runtime.answer.gradeFlashcard(true);await automationFrame();return {ok:flash&&media&&back&&runtime.answer.feedback&&runtime.answer.feedback.correct,flash,media,back};});
      await runStep('full session answers qcm/fill/matching/order/flashcard with one injected error',async()=>{runtime.session.start();runtime.answer.reset();runtime.go('session');await automationFrame();const seen={};let injected=false;const answered=[];let guard=0;while(runtime.session.session.status==='active'&&guard++<80){const a=runtime.session.currentActivity();seen[a.type]=(seen[a.type]||0)+1;const shouldBeCorrect=injected?true:false;injected=true;const ar=automationAnswerCurrent(runtime,shouldBeCorrect);answered.push(ar);if(!ar.ok)return {ok:false,detail:'answer mismatch',answered};runtime.answer.continue();await automationFrame();}const bilan=runtime.appState.state.lastBilan;return {ok:runtime.appState.view==='bilan'&&runtime.session.session.status==='completed'&&bilan.review.length===1&&['qcm','fill','matching','order','flashcard'].every(t=>seen[t]>0),view:runtime.appState.view,status:runtime.session.session.status,seen,review:bilan.review,answered:answered.length};});
      await runStep('targeted remediation closes loop',async()=>{const review=runtime.appState.state.lastBilan.review;runtime.session.startTargetedReview(review,{summary:'automation targeted review',focus:'corriger erreur injectée',objectives:review,hints:['répondre correctement']});runtime.answer.reset();runtime.go('session');await automationFrame();let guard=0;const answered=[];while(runtime.session.session.status==='active'&&guard++<20){const ar=automationAnswerCurrent(runtime,true);answered.push(ar);if(!ar.ok)return {ok:false,detail:'targeted answer mismatch',answered};runtime.answer.continue();await automationFrame();}const bilan=runtime.appState.state.lastBilan;return {ok:runtime.appState.view==='bilan'&&bilan.mode==='targeted-review'&&bilan.review.length===0,view:runtime.appState.view,mode:bilan.mode,review:bilan.review,answered:answered.length};});
      await runStep('bilan projections and learning loop exportable',async()=>{const enriched=window.__LEARNIT_TEST__.enrichedBilan();const loop=window.__LEARNIT_TEST__.learningLoop();return {ok:!!(enriched&&loop),enrichedSummary:enriched&&enriched.summary,loopStatus:loop&&loop.status};});
      await runStep('per-course bilan scope is non-blocking',async()=>{const courses=runtime.contentStore.courseList().filter(c=>c.courseId!==importedCourseId);const aCourse=courses[0], bCourse=courses[1]||courses[0];if(!aCourse||!bCourse)return {ok:false,detail:'not enough courses'};runtime.contentStore.setActiveCourse(aCourse.courseId);runtime.appState.alignWithContent();runtime.answer.reset();const first=runtime.contentStore.content.activities[0];runtime.session.startTargetedReview([first.id],{summary:'course A wrong evidence'});runtime.answer.reset();runtime.go('session');await automationFrame();const wrong=automationAnswerCurrent(runtime,false);runtime.answer.continue();await automationFrame();const reviewA=(runtime.appState.state.lastBilan&&runtime.appState.state.lastBilan.review||[]).length;runtime.contentStore.setActiveCourse(bCourse.courseId);runtime.appState.alignWithContent();runtime.answer.reset();runtime.go('bilan');await automationFrame();const reviewB=(runtime.appState.state.lastBilan&&runtime.appState.state.lastBilan.review||[]).length;const hasAnyB=buildBilanProjection(runtime).hasAny;runtime.contentStore.setActiveCourse(aCourse.courseId);runtime.appState.alignWithContent();runtime.answer.reset();runtime.go('bilan');await automationFrame();const restoredA=(runtime.appState.state.lastBilan&&runtime.appState.state.lastBilan.review||[]).length;return {ok:wrong.ok&&reviewA===1&&reviewB===0&&!hasAnyB&&restoredA===1,courseA:aCourse.courseId,courseB:bCourse.courseId,reviewA,reviewB,restoredA,hasAnyB};});
      await runStep('library course KPIs are scoped and selected card is source of truth',async()=>{const courses=runtime.contentStore.courseList();const aCourse=courses[0], bCourse=courses[1]||courses[0];if(!aCourse||!bCourse)return {ok:false,detail:'not enough courses'};runtime.contentStore.setActiveCourse(aCourse.courseId);runtime.appState.alignWithContent();runtime.answer.reset();const first=runtime.contentStore.content.activities[0];runtime.session.startTargetedReview([first.id],{summary:'rc158 scoped KPI evidence'});runtime.answer.reset();runtime.go('session');await automationFrame();const wrong=automationAnswerCurrent(runtime,false);runtime.answer.continue();await automationFrame();runtime.go('library');await automationFrame();const textA=runtime.root.innerText;const kpisA=buildLibraryProjection(runtime).courses;const kA=kpisA.find(c=>c.courseId===aCourse.courseId);runtime.contentStore.setActiveCourse(bCourse.courseId);runtime.appState.alignWithContent();runtime.answer.reset();runtime.go('library');await automationFrame();const textB=runtime.root.innerText;const kpisB=buildLibraryProjection(runtime).courses;const kB=kpisB.find(c=>c.courseId===bCourse.courseId);const kA2=kpisB.find(c=>c.courseId===aCourse.courseId);const selectedBlockAbsent=!new RegExp('Parcours s'+'électionné','i').test(textA+textB)&&!/Actif\s*:/i.test(textA+textB);const cardCtaPresent=/Reprendre|Continuer|Commencer|Consolider|Bibliothèque/.test(textA)&&/Reprendre|Continuer|Commencer|Consolider|Bibliothèque/.test(textB);const noDuplicateKpiBoxes=!/Voir les indicateurs|progression\s*$/i.test(textA+textB);const scoped=!!(kA&&kA.kpi.reviewCount>0&&kA.kpi.status==='À revoir'&&kB&&kB.kpi.reviewCount===0&&kA2&&kA2.kpi.reviewCount>0);return {ok:wrong.ok&&selectedBlockAbsent&&cardCtaPresent&&noDuplicateKpiBoxes&&scoped,courseA:aCourse.courseId,courseB:bCourse.courseId,kpiA:kA&&kA.kpi,kpiB:kB&&kB.kpi,kpiAAfterSwitch:kA2&&kA2.kpi,selectedBlockAbsent,cardCtaPresent,noDuplicateKpiBoxes,scoped};});
      await runStep('rollback import restores library base',async()=>{const before=runtime.contentStore.imported.length;const rb=runtime.contentStore.rollbackImport();runtime.appState.alignWithContent();runtime.answer.reset();runtime.go('library');await automationFrame();const remaining=runtime.contentStore.imported.length;const activeExists=runtime.contentStore.courseList().some(c=>c.courseId===runtime.contentStore.activeCourseId);const ok=rb.ok&&before>0&&remaining===0&&activeExists; if(ok){runtime.appState.resetAll(); runtime.appState.alignWithContent(); runtime.answer.reset(); runtime.go('learn'); await automationFrame();} return {ok,before,remaining,activeCourseId:runtime.contentStore.activeCourseId,rollback:rb};});
      await runStep('final static gates',async()=>{const gates=window.__LEARNIT_TEST__.gates();const runtimeReport=window.__LEARNIT_TEST__.runtimeReport();return {ok:gates.ok&&runtimeReport.ok,gates,runtimeReport};});
      const ok=results.every(r=>r.ok);const report={schema:'learnit.automation.golden_path.v1',version:VERSION_LABEL,ok,startedAt:started,endedAt:new Date().toISOString(),environment:{userAgent:navigator.userAgent,viewport:{width:innerWidth,height:innerHeight},headless:!!(options&&options.headless)},summary:ok?'AUTOMATED GOLDEN PATH PASS':'AUTOMATED GOLDEN PATH HOLD',counts:{steps:results.length,passed:results.filter(r=>r.ok).length,failed:results.filter(r=>!r.ok).length},results};window.__LEARNIT_AUTOMATION_LAST_REPORT__=report;return report;
    }
    function automationDownloadLastReport(){const report=window.__LEARNIT_AUTOMATION_LAST_REPORT__||{ok:false,summary:'Aucun rapport exécuté'};const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='learnit_rc186_automated_golden_path_report.json';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);}
    window.__LEARNIT_AUTOMATION__={version:VERSION_LABEL,testKit:AUTOMATION_TEST_KIT,runGoldenPath:automationRunGoldenPath,downloadLastReport:automationDownloadLastReport};
    window.__LEARNIT_DEFERRED_BOOT__=function(){return runtime.boot();};
  })();
