'use strict';
const E=require('../core/atlas_events.js');
const {projectObjectiveEvidence}=require('../core/atlas_projection.js');
class InMemoryAtlasStorage{
 constructor(){this.namespace='learnit.atlas.m1.v2';this.learningEvents=[];this.scoredExecutions=[];this.resumeStates=[];this.atlasMeta={startOrdinal:0,startRequests:{},sessions:{},assistanceUses:{}};this.failNext=false;}
 snapshot(){return structuredClone({learningEvents:this.learningEvents,scoredExecutions:this.scoredExecutions,resumeStates:this.resumeStates,atlasMeta:this.atlasMeta});}
 atomic(mutator){const draft=this.snapshot();mutator(draft);if(this.failNext){this.failNext=false;throw Object.assign(new Error('FAULT_INJECTED'),{code:'FAULT_INJECTED'});}Object.assign(this,draft);return true;}
 injectFailure(){this.failNext=true;}
}
function getResume(state,sessionId){return state.resumeStates.find(x=>x.sessionRef.sessionId===sessionId);}
function assertUnique(rows,key,code){const seen=new Set();for(const row of rows){const value=key(row);if(seen.has(value))E.fail(code);seen.add(value);}return seen;}
function validateAtlasMeta(meta){
 E.assertClosed(meta,['startOrdinal','startRequests','sessions','assistanceUses'],[],'INVALID_ATLAS_META');if(!Number.isInteger(meta.startOrdinal)||meta.startOrdinal<0||!E.isObject(meta.startRequests)||!E.isObject(meta.sessions)||!E.isObject(meta.assistanceUses))E.fail('INVALID_ATLAS_META');
 for(const [id,record] of Object.entries(meta.startRequests)){E.assertClosed(record,['schemaVersion','startRequestId','planDigest','startOrdinal','preparedAt']);if(record.schemaVersion!=='atlas.start-request.v1'||id!==record.startRequestId||!E.IDS.start.test(id)||!E.SHA.test(record.planDigest)||!Number.isInteger(record.startOrdinal)||record.startOrdinal<1)E.fail('INVALID_ATLAS_META');require('../core/atlas_clock.js').assertCanonicalTimestamp(record.preparedAt);}
 for(const [id,session] of Object.entries(meta.sessions)){E.assertClosed(session,['sessionRef','plan']);E.assertSessionRef(session.sessionRef);E.validatePlan(session.plan);if(id!==session.sessionRef.sessionId||session.sessionRef.planId!==session.plan.planId)E.fail('INVALID_ATLAS_META');}
 for(const [id,record] of Object.entries(meta.assistanceUses)){E.assertClosed(record,['assistanceVersion','assistanceUseId','sessionRef','itemPosition','assistanceKind','recordedAt']);if(record.assistanceVersion!=='atlas.assistance-use.v1'||id!==record.assistanceUseId||!E.IDS.assistance.test(id)||!Number.isInteger(record.itemPosition)||record.itemPosition<0||!['hint','guided-step','revealing-feedback','solution','previous-answer'].includes(record.assistanceKind))E.fail('INVALID_ATLAS_META');E.assertSessionRef(record.sessionRef);require('../core/atlas_clock.js').assertCanonicalTimestamp(record.recordedAt);}
 return meta;
}
function validateImport(payload){
 E.assertClosed(payload,['atlasStateVersion','namespace','exportedAt','contentRevisionDigests','learningEvents','scoredExecutions','resumeStates','atlasMeta'],[],'INVALID_IMPORT');
 if(payload.atlasStateVersion!=='0.3'||payload.namespace!=='learnit.atlas.m1.v2')E.fail('UNSUPPORTED_ATLAS_STATE_VERSION');require('../core/atlas_clock.js').assertCanonicalTimestamp(payload.exportedAt);
 if(!Array.isArray(payload.contentRevisionDigests)||payload.contentRevisionDigests.some(x=>!E.SHA.test(x))||!Array.isArray(payload.learningEvents)||!Array.isArray(payload.scoredExecutions)||!Array.isArray(payload.resumeStates))E.fail('INVALID_IMPORT');
 const executionIds=assertUnique(payload.scoredExecutions,x=>{E.validateScoredExecution(x);return x.executionId;},'DUPLICATE_EXECUTION_ID');
 const eventIds=assertUnique(payload.learningEvents,x=>{if(['activity-attempt','activity-corrected'].includes(x.kind))E.validatePedagogicalEvent(x);else if(x.kind==='session-started')validateStartedEvent(x);else validateLifecycleEvent(x);return x.eventId;},'DUPLICATE_EVENT_ID');
 const resumeIds=assertUnique(payload.resumeStates,x=>{E.validateResumeState(x);return x.sessionRef.sessionId;},'DUPLICATE_RESUME_STATE');validateAtlasMeta(payload.atlasMeta);
 for(const event of payload.learningEvents)if(['activity-attempt','activity-corrected'].includes(event.kind)&&!executionIds.has(event.executionId))E.fail('MISSING_EXECUTION');
 for(const resume of payload.resumeStates)if(!payload.atlasMeta.sessions[resume.sessionRef.sessionId])E.fail('RESUME_SESSION_NOT_FOUND');
 for(const sessionId of Object.keys(payload.atlasMeta.sessions))if(!resumeIds.has(sessionId))E.fail('SESSION_RESUME_NOT_FOUND');
 return payload;
}

function validateStartedEvent(event){
 E.assertClosed(event,['eventVersion','eventId','eventOrdinal','kind','sessionRef','courseRef','contentRevisionRef','planDigest','selectedItems','occurredAt'],[],'INVALID_STARTED_EVENT');
 if(event.eventVersion!=='atlas.learning-event.v1'||event.kind!=='session-started'||event.eventOrdinal!==0||!E.IDS.event.test(event.eventId)||!E.SHA.test(event.planDigest)||!Array.isArray(event.selectedItems))E.fail('INVALID_STARTED_EVENT');
 E.assertSessionRef(event.sessionRef);E.assertCourseRef(event.courseRef);E.assertContentRevisionRef(event.contentRevisionRef);require('../core/atlas_clock.js').assertCanonicalTimestamp(event.occurredAt);
 event.selectedItems.forEach((item,index)=>E.validatePlanItem(item,index));
 const identity={eventVersion:event.eventVersion,kind:event.kind,sessionRef:event.sessionRef,planDigest:event.planDigest,eventOrdinal:0};
 if(event.eventId!==E.eventId(identity))E.fail('EVENT_ID_INVALID');return event;
}
function validateLifecycleEvent(event){
 E.assertClosed(event,['eventVersion','eventId','eventOrdinal','kind','sessionRef','occurredAt'],[],'INVALID_LIFECYCLE_EVENT');if(event.eventVersion!=='atlas.learning-event.v1'||!E.IDS.event.test(event.eventId)||!Number.isInteger(event.eventOrdinal)||event.eventOrdinal<1||!['session-interrupted','session-resumed','session-completed'].includes(event.kind))E.fail('INVALID_LIFECYCLE_EVENT');E.assertSessionRef(event.sessionRef);require('../core/atlas_clock.js').assertCanonicalTimestamp(event.occurredAt);const expected=E.eventId(Object.fromEntries(Object.entries(event).filter(([k])=>k!=='eventId')));if(event.eventId!==expected)E.fail('EVENT_ID_INVALID');return event;
}
class AtlasCoreService{
 constructor({storage,clock,registry}){this.storage=storage;this.clock=clock;this.registry=registry;}
 prepareStartRequest(planDigest){if(!E.SHA.test(planDigest))E.fail('INVALID_PLAN_DIGEST');let record;this.storage.atomic(s=>{const ordinal=++s.atlasMeta.startOrdinal;const payload={planDigest,startOrdinal:ordinal};record={schemaVersion:'atlas.start-request.v1',startRequestId:E.startRequestId(payload),planDigest,startOrdinal:ordinal,preparedAt:this.clock.now()};s.atlasMeta.startRequests[record.startRequestId]=record;});return E.deepFreeze(record);}
 startSession(startRequestId,plan){E.validatePlan(plan);const request=this.storage.atlasMeta.startRequests[startRequestId];if(!request)E.fail('START_REQUEST_NOT_FOUND');if(request.planDigest!==plan.planDigest)E.fail('START_REQUEST_PLAN_CONFLICT');const sid=E.sessionId({startRequestId,planDigest:plan.planDigest});if(this.storage.atlasMeta.sessions[sid])return E.deepFreeze(structuredClone(this.storage.atlasMeta.sessions[sid].sessionRef));let sessionRef={sessionId:sid,planId:plan.planId};this.storage.atomic(s=>{const eventPayload={eventVersion:'atlas.learning-event.v1',kind:'session-started',sessionRef,planDigest:plan.planDigest,eventOrdinal:0};const started={...eventPayload,eventId:E.eventId(eventPayload),courseRef:plan.payload.courseRef,contentRevisionRef:plan.payload.contentRevisionRef,selectedItems:plan.payload.items,occurredAt:this.clock.now()};s.learningEvents.push(started);s.resumeStates.push({resumeVersion:'atlas.resume-state.v1',sessionRef,courseRef:plan.payload.courseRef,contentRevisionRef:plan.payload.contentRevisionRef,planDigest:plan.planDigest,nextItemPosition:0,focusTarget:'atlas-session-item-0',lifecycleOrdinal:0,itemStates:plan.payload.items.map(x=>({itemPosition:x.position,submissionOrdinal:0,assistance:'none',assistanceUseIds:[]}))});s.atlasMeta.sessions[sid]={sessionRef,plan};});return E.deepFreeze(sessionRef);}
 requestAssistance(sessionId,itemPosition,assistanceKind){if(!['hint','guided-step','revealing-feedback','solution','previous-answer'].includes(assistanceKind))E.fail('UNKNOWN_ASSISTANCE_KIND');let rec;this.storage.atomic(s=>{const resume=getResume(s,sessionId);if(!resume)E.fail('SESSION_NOT_FOUND');const item=resume.itemStates.find(x=>x.itemPosition===itemPosition);if(!item)E.fail('ITEM_NOT_FOUND');const payload={sessionRef:resume.sessionRef,itemPosition,assistanceKind,recordedAt:this.clock.now()};rec={assistanceVersion:'atlas.assistance-use.v1',assistanceUseId:E.assistanceUseId(payload),...payload};item.assistance='used';if(!item.assistanceUseIds.includes(rec.assistanceUseId))item.assistanceUseIds.push(rec.assistanceUseId);s.atlasMeta.assistanceUses[rec.assistanceUseId]=rec;});return E.deepFreeze({committed:true,record:rec});}
 commitActivitySubmission(sessionId,itemPosition,rawResponse){let result;this.storage.atomic(s=>{const session=s.atlasMeta.sessions[sessionId],resume=getResume(s,sessionId);if(!session||!resume)E.fail('SESSION_NOT_FOUND');const planItem=session.plan.payload.items[itemPosition];if(!planItem||planItem.position!==itemPosition)E.fail('ITEM_NOT_FOUND');const activity=this.registry.activity(planItem.activityRef);if(!activity)E.fail('ACTIVE_ACTIVITY_NOT_FOUND');const state=resume.itemStates.find(x=>x.itemPosition===itemPosition),submissionOrdinal=state.submissionOrdinal+1,scoringRule={id:activity.scoringRuleId,type:activity.type,answer:activity.answer},outcome=activity.score(rawResponse)?'correct':'incorrect';
   if(planItem.executionClass==='validation'&&typeof this.registry.validateClaim==='function'&&!this.registry.validateClaim(planItem,{outcome,assistance:state.assistance||'unknown'}))E.fail('VALIDATION_CLAIM_NOT_ACCEPTED');
   const base={executionVersion:'atlas.scored-execution.v1',sessionRef:resume.sessionRef,courseRef:resume.courseRef,contentRevisionRef:resume.contentRevisionRef,planDigest:resume.planDigest,itemPosition,submissionOrdinal,objectiveRef:planItem.objectiveRef,activityRef:planItem.activityRef,action:planItem.action,executionClass:planItem.executionClass,responseDigest:E.responseDigest(rawResponse),scoringRuleId:activity.scoringRuleId,scoringRuleDigest:E.scoringRuleDigest(scoringRule),outcome,assistance:state.assistance||'unknown',assistanceUseIds:[...state.assistanceUseIds],submittedAt:this.clock.now(),scoredAt:this.clock.now()};const executionId=E.executionId(base),execution=E.deepFreeze({...base,executionId});E.validateScoredExecution(execution);
   const kind=planItem.executionClass==='correction'?'activity-corrected':'activity-attempt',eventBase={eventVersion:'atlas.learning-event.v1',kind,objectiveRef:planItem.objectiveRef,executionId,occurredAt:this.clock.now()};if(kind==='activity-corrected'){if(!planItem.correctsEventId)E.fail('CORRECTS_EVENT_ID_REQUIRED');const target=s.learningEvents.find(x=>x.eventId===planItem.correctsEventId),targetExec=target&&s.scoredExecutions.find(x=>x.executionId===target.executionId);if(!target||!targetExec||targetExec.executionClass!=='practice'||targetExec.outcome!=='incorrect'||E.canonicalJson(target.objectiveRef)!==E.canonicalJson(planItem.objectiveRef))E.fail('INVALID_CORRECTION_TARGET');eventBase.correctsEventId=planItem.correctsEventId;}const event=E.deepFreeze({...eventBase,eventId:E.eventId(eventBase)});E.validatePedagogicalEvent(event);
   const oldExecution=s.scoredExecutions.find(x=>x.executionId===execution.executionId);if(oldExecution&&E.canonicalJson(oldExecution)!==E.canonicalJson(execution))E.fail('IDENTITY_PAYLOAD_CONFLICT');if(!oldExecution)s.scoredExecutions.push(execution);const oldEvent=s.learningEvents.find(x=>x.eventId===event.eventId);if(oldEvent&&E.canonicalJson(oldEvent)!==E.canonicalJson(event))E.fail('IDENTITY_PAYLOAD_CONFLICT');if(!oldEvent)s.learningEvents.push(event);state.submissionOrdinal=submissionOrdinal;resume.lastCommittedEventId=event.eventId;resume.nextItemPosition=Math.min(itemPosition+1,session.plan.payload.items.length);resume.focusTarget=resume.nextItemPosition<session.plan.payload.items.length?`atlas-session-item-${resume.nextItemPosition}`:'atlas-session-summary';result={execution,event,resumeState:structuredClone(resume)};});return E.deepFreeze(result);}
 lifecycle(sessionId,kind){if(!['session-interrupted','session-resumed','session-completed'].includes(kind))E.fail('UNKNOWN_EVENT_KIND');let event;this.storage.atomic(s=>{const resume=getResume(s,sessionId);if(!resume)E.fail('SESSION_NOT_FOUND');const ordinal=++resume.lifecycleOrdinal,base={eventVersion:'atlas.learning-event.v1',kind,sessionRef:resume.sessionRef,eventOrdinal:ordinal,occurredAt:this.clock.now()};event={...base,eventId:E.eventId(base)};validateLifecycleEvent(event);s.learningEvents.push(event);});return E.deepFreeze(event);}
 evidence(){return projectObjectiveEvidence(this.storage.learningEvents,this.storage.scoredExecutions,(execution)=>execution.assistance==='none'&&['attempt-validation','maintain-recent-validation'].includes(execution.action));}
 exportState(){return {atlasStateVersion:'0.3',namespace:'learnit.atlas.m1.v2',exportedAt:this.clock.now(),contentRevisionDigests:[],...this.storage.snapshot()};}
 importState(payload){if(!payload||payload.atlasStateVersion!=='0.3'||payload.namespace!=='learnit.atlas.m1.v2')E.fail('UNSUPPORTED_ATLAS_STATE_VERSION');validateImport(payload);this.storage.atomic(s=>{s.learningEvents=structuredClone(payload.learningEvents);s.scoredExecutions=structuredClone(payload.scoredExecutions);s.resumeStates=structuredClone(payload.resumeStates);s.atlasMeta=structuredClone(payload.atlasMeta);});return true;}
}
module.exports=Object.freeze({InMemoryAtlasStorage,AtlasCoreService,validateImport,validateAtlasMeta,validateStartedEvent,validateLifecycleEvent});
