#!/usr/bin/env python3
from __future__ import annotations
import hashlib, json
from support import ROOT, active_script_paths
R=ROOT/'src/scripts/core/runtime_parts'; B=R/'00_runtime_boot_and_content_library.js'; P=R/'04_local_storage_port.js'; D=R/'05_durable_library_store.js'; PR='src/scripts/core/runtime_parts/04_local_storage_port.js'
PORT_SHA='ac552c7daad97daab2a436170416324557bc5bd6a83944a1b144e5985a7567c3'; RUNTIME_FP='a2baa53db1c4d232073b79bf4f08c7245b756182dc3a98b830187fdddee32fca'; NORMAL_FP='d9d078c482250ccdc63042823a7dcab9662d117135d504c686fbb9eefdec2d73'
KEYS=('learnit_clean_state_v2','learnit_clean_journal_v2','learnit_content_patches_v2','learnit_active_course_v1','learnit_field_evidence_v1','learnit_imported_courses_v1','learnit_import_history_v1','learnit_import_last_applied_v1','learnit_import_transaction_v1','learnit_recovery_report_v1','learnit_resilience_meta_v1','learnit_library_revision_v1','learnit_library_persistence_meta_v1')
def main()->int:
 b=B.read_text(); pb=P.read_bytes() if P.exists() else b''; p=pb.decode() if pb else ''; d=D.read_text(); o=json.loads((ROOT/'docs/OWNER_MAP.json').read_text())['owners']; g=json.loads((ROOT/'dev/checks_registry.json').read_text()); c=json.loads((ROOT/'dev/release_config.json').read_text()); s={x.name:x.read_text() for x in sorted(R.glob('*.js'))}; a=active_script_paths(); z=a.index('src/scripts/core/runtime_parts/00_runtime_boot_and_content_library.js') if 'src/scripts/core/runtime_parts/00_runtime_boot_and_content_library.js' in a else -1
 q=[('local-owner',[n for n,v in s.items() if 'window.localStorage' in v]==[P.name]),('idb-owner',[n for n,v in s.items() if 'indexedDB.open(' in v or 'window.indexedDB.open(' in v]==[D.name]),('boot-clean','const storage = (()=>{' not in b),('adapter-bytes',hashlib.sha256(pb).hexdigest()==PORT_SHA),('keys',all(k in b+d for k in KEYS)),('order',z>=0 and a[z:z+4]==[a[z],PR,'src/scripts/core/runtime_parts/05_durable_library_store.js','src/scripts/core/runtime_parts/10_content_store_and_state.js']),('owner-map',o.get(PR)=='synchronous-local-storage-port-memory-fallback-telemetry-and-fault-injection'),('registered',g.get('mandatory',[]).count('tests/contract_storage_boundary.py')==1),('ignored',c.get('baseline_equivalence',{}).get('ignored_script_paths',[]).count(PR)==1),('runtime-fp',c.get('runtime_fingerprint')==RUNTIME_FP),('normalized-fp',c.get('baseline_equivalence',{}).get('runtime_js_normalized_sha256')==NORMAL_FP),('no-expansion',not any(x in p for x in ('indexedDB','fetch(','XMLHttpRequest','WebSocket','http://','https://')))]
 ok=all(v for _,v in q); out=ROOT/'reports/contract_storage_boundary_report.json'; out.parent.mkdir(exist_ok=True); out.write_text(json.dumps({'schema':'learnit.first_storage_seam_contract.v1','ok':ok,'checks':[{'code':k,'ok':v} for k,v in q]},indent=2)+'\n'); print(json.dumps({'ok':ok,'passed':sum(v for _,v in q),'total':len(q),'report':str(out.relative_to(ROOT))},indent=2)); return 0 if ok else 1
if __name__=='__main__': raise SystemExit(main())
