(()=>{
'use strict';
const {el,emit,stage,header,status,primary,pointerDrag}=window.__LAB_CORE__;
function lessonA(v,p){const btn=primary('Continuer',()=>{emit({acknowledged:true});btn.disabled=true});stage.append(header(v,'Lecture simple.'),el('article',{class:'activity-card'},[el('h3',{text:p.title}),el('p',{text:p.body}),el('ul',{},p.keyPoints.map(x=>el('li',{text:x}))),el('p',{class:'muted',text:p.contextNote}),el('div',{class:'actions'},[btn])]))}
window.__LAB_RENDERERS__['lesson-a']=lessonA;
function flashA(v,p){let revealed=false;const back=el('div',{class:'flash-a-back'},[el('strong',{text:p.back}),el('p',{text:p.explanation})]);back.hidden=true;const reveal=el('button',{type:'button',text:'Afficher la réponse'});const cont=primary('Continuer',()=>revealed&&emit({revealed:true}));cont.hidden=true;reveal.addEventListener('click',()=>{revealed=true;back.hidden=false;reveal.remove();cont.hidden=false;cont.focus()});stage.append(header(v,'Baseline fonctionnelle.'),el('article',{class:'activity-card'},[el('p',{text:p.front}),back,el('div',{class:'actions'},[reveal,cont])]))}
window.__LAB_RENDERERS__['flashcard-a']=flashA;
function matchingA(v,p){const map=new Map();let selected=null;const st=status('Choisis un terme à gauche puis une description à droite.');const left=el('div',{class:'baseline-column'}),right=el('div',{class:'baseline-column'}),summary=el('div',{class:'association-summary'});const paint=()=>{summary.replaceChildren(...p.leftItems.filter(i=>map.has(i.itemId)).map(i=>el('div',{class:'association-row'},[el('span',{text:i.label}),el('span',{text:'→'}),el('span',{text:p.rightItems.find(r=>r.itemId===map.get(i.itemId)).label})])));st.textContent=`${map.size}/${p.leftItems.length} association(s).`};p.leftItems.forEach(i=>{const b=el('button',{type:'button',class:'choice',text:i.label,'aria-pressed':'false'});b.onclick=()=>{selected=i.itemId;left.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));st.textContent='Choisis maintenant une description.'};left.append(b)});p.rightItems.forEach(i=>{const b=el('button',{type:'button',text:i.label});b.onclick=()=>{if(!selected)return;for(const[k,r]of[...map])if(k===selected||r===i.itemId)map.delete(k);map.set(selected,i.itemId);selected=null;left.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed','false'));paint()};right.append(b)});const send=primary('Émettre la réponse',()=>{if(map.size!==p.leftItems.length){st.textContent='Associe chaque terme avant de continuer.';return}emit({associations:p.leftItems.map(i=>({leftItemId:i.itemId,rightItemId:map.get(i.itemId)}))})});stage.append(header(v,'Baseline fonctionnelle.'),el('p',{text:p.prompt}),el('div',{class:'baseline-pair'},[left,right]),summary,st,el('div',{class:'actions'},[send]))}
window.__LAB_RENDERERS__['matching-a']=matchingA;
function orderA(v,p){const list=el('div',{class:'stack'});p.items.forEach(i=>{const row=el('div',{class:'order-a-row','data-id':i.itemId},[el('span',{text:i.label})]),controls=el('span',{class:'order-a-controls'}),up=el('button',{type:'button','aria-label':`Monter ${i.label}`,text:'↑'}),down=el('button',{type:'button','aria-label':`Descendre ${i.label}`,text:'↓'});up.onclick=()=>{if(row.previousElementSibling)list.insertBefore(row,row.previousElementSibling)};down.onclick=()=>{if(row.nextElementSibling)list.insertBefore(row.nextElementSibling,row)};controls.append(up,down);row.append(controls);list.append(row)});const send=primary('Émettre la réponse',()=>emit({orderedItemIds:[...list.children].map(x=>x.dataset.id)}));stage.append(header(v,'Baseline fonctionnelle.'),el('p',{text:p.prompt}),list,el('div',{class:'actions'},[send]))}
window.__LAB_RENDERERS__['order-a']=orderA;
function classifyA(v,p){const values=new Map(p.items.map(i=>[i.itemId,''])),list=el('div',{class:'stack'}),st=status('');p.items.forEach(i=>{const s=el('select',{'aria-label':`Catégorie pour ${i.label}`},[el('option',{value:'',text:'Choisir…'}),...p.buckets.map(b=>el('option',{value:b.bucketId,text:b.label}))]);s.onchange=()=>values.set(i.itemId,s.value);list.append(el('div',{class:'classify-a-row'},[el('span',{text:i.label}),s]))});const send=primary('Émettre la réponse',()=>{if([...values.values()].some(x=>!x)){st.textContent='Classe tous les éléments.';return}emit({assignments:p.items.map(i=>({itemId:i.itemId,bucketId:values.get(i.itemId)}))})});stage.append(header(v,'Baseline fonctionnelle.'),el('p',{text:p.prompt}),list,st,el('div',{class:'actions'},[send]))}
window.__LAB_RENDERERS__['classify-a']=classifyA;
function qcmA(v,p){const fs=el('fieldset',{class:'qcm-options'});fs.append(el('legend',{text:p.prompt}));p.choices.forEach(c=>{const input=el('input',{type:'radio',name:'qcm',value:c.choiceId}),label=el('label',{class:'qcm-option'},[input,el('span',{class:'qcm-label',text:c.label})]);fs.append(label)});const send=primary('Émettre la réponse',()=>{const x=fs.querySelector('input:checked');if(x)emit({choiceId:x.value})});stage.append(header(v,'Baseline conservée, avec texte aligné immédiatement après le bouton radio et retour à la ligne robuste.'),fs,el('div',{class:'actions'},[send]))}
window.__LAB_RENDERERS__['qcm-a']=qcmA;
function fillA(v,p){const sentence=el('p',{class:'fill-a-sentence'});p.segments.forEach(seg=>{if(seg.text)sentence.append(seg.text);else sentence.append(el('select',{'data-slot':seg.slotId,'aria-label':`Réponse ${seg.slotId}`},[el('option',{value:'',text:'Choisir…'}),...p.tokens.map(t=>el('option',{value:t.tokenId,text:t.label}))]))});const send=primary('Émettre la réponse',()=>{const out={};for(const s of sentence.querySelectorAll('select')){if(!s.value)return;out[s.dataset.slot]=s.value}emit(out)});stage.append(header(v,'Baseline fonctionnelle.'),el('p',{text:p.prompt}),sentence,el('div',{class:'actions'},[send]))}
window.__LAB_RENDERERS__['fill-a']=fillA;
})();
