'use strict';
const REASON_LABELS=Object.freeze({NEW_OBJECTIVE:'Nouvel objectif à découvrir.',PRACTICE_IN_PROGRESS:'Entraînement en cours.',RECENT_ERROR:'Une erreur récente doit être reprise.',REVIEW_REQUIRED:'Une correction ciblée est recommandée.',CORRECTION_COMPLETED:'La correction a été effectuée.',NO_INDEPENDENT_VALIDATION:'Aucune validation indépendante admissible.',VALIDATION_AVAILABLE:'Une validation autonome est disponible.',RECENTLY_VALIDATED:'Une validation récente est enregistrée.',SESSION_TIME_LIMIT:'Cette activité ne tient pas dans la durée choisie.'});
const ACTION_CLASS=Object.freeze({'start-practice':'practice','continue-practice':'practice','correct-practice':'correction','attempt-validation':'validation','maintain-recent-validation':'validation'});
function fail(code){const e=new Error(code);e.code=code;throw e;}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function isObject(v){return v!==null&&typeof v==='object'&&!Array.isArray(v);}
function assertClosed(v,required,optional=[]){if(!isObject(v))fail('INVALID_OBJECT');const allowed=new Set([...required,...optional]);for(const k of Object.keys(v))if(!allowed.has(k))fail('UNKNOWN_FIELD');for(const k of required)if(!(k in v))fail('MISSING_FIELD');return v;}
function courseKey(ref){assertClosed(ref,['packageLineageId','courseLineageId']);if(typeof ref.packageLineageId!=='string'||!ref.packageLineageId||typeof ref.courseLineageId!=='string'||!ref.courseLineageId)fail('INVALID_COURSE_REF');return `${ref.packageLineageId}\0${ref.courseLineageId}`;}
function objectiveKey(ref){assertClosed(ref,['courseRef','objectiveId']);if(typeof ref.objectiveId!=='string'||!ref.objectiveId)fail('INVALID_OBJECTIVE_REF');return `${courseKey(ref.courseRef)}\0${ref.objectiveId}`;}
function activityKey(ref){assertClosed(ref,['courseRef','activityLineageId']);if(typeof ref.activityLineageId!=='string'||!ref.activityLineageId)fail('INVALID_ACTIVITY_REF');return `${courseKey(ref.courseRef)}\0${ref.activityLineageId}`;}
function validateRecommendation(rec){
 assertClosed(rec,['recommendationVersion','objectiveRef','action','eligibleActivityRefs','preferredActivityRef','estimatedMinutes','reasonCodes']);
 if(rec.recommendationVersion!=='atlas.recommendation.v1'||!ACTION_CLASS[rec.action])fail('INVALID_RECOMMENDATION');objectiveKey(rec.objectiveRef);activityKey(rec.preferredActivityRef);
 if(courseKey(rec.objectiveRef.courseRef)!==courseKey(rec.preferredActivityRef.courseRef)||!Array.isArray(rec.eligibleActivityRefs)||!rec.eligibleActivityRefs.length||!rec.eligibleActivityRefs.some(x=>activityKey(x)===activityKey(rec.preferredActivityRef)))fail('INVALID_RECOMMENDATION');
 if(!Number.isInteger(rec.estimatedMinutes)||rec.estimatedMinutes<1||rec.estimatedMinutes>30||!Array.isArray(rec.reasonCodes)||!rec.reasonCodes.length||new Set(rec.reasonCodes).size!==rec.reasonCodes.length||rec.reasonCodes.some(x=>!REASON_LABELS[x]))fail('INVALID_RECOMMENDATION');return rec;
}
function validatePlanItem(item,index){
 const optional=item&&item.action==='correct-practice'?['correctsEventId']:item&&['attempt-validation','maintain-recent-validation'].includes(item.action)?['validationBasisEventId','independenceClaimId']:[];
 assertClosed(item,['position','objectiveRef','activityRef','action','executionClass','estimatedMinutes'],optional);if(item.position!==index||ACTION_CLASS[item.action]!==item.executionClass||!Number.isInteger(item.estimatedMinutes)||item.estimatedMinutes<1||item.estimatedMinutes>30)fail('INVALID_SESSION_PLAN');
 objectiveKey(item.objectiveRef);activityKey(item.activityRef);if(courseKey(item.objectiveRef.courseRef)!==courseKey(item.activityRef.courseRef))fail('INVALID_SESSION_PLAN');return item;
}
function validatePlan(plan){
 assertClosed(plan,['planId','planDigest','payload']);if(!/^atlas-plan-sha256:[0-9a-f]{64}$/.test(plan.planId)||!/^sha256:[0-9a-f]{64}$/.test(plan.planDigest))fail('INVALID_SESSION_PLAN');
 assertClosed(plan.payload,['schemaVersion','engineVersion','courseRef','contentRevisionRef','durationMinutes','items','totalEstimatedMinutes','unusedMinutes']);if(plan.payload.schemaVersion!=='atlas.session-plan.v1'||!Array.isArray(plan.payload.items)||![5,15,30].includes(plan.payload.durationMinutes))fail('INVALID_SESSION_PLAN');courseKey(plan.payload.courseRef);
 let total=0;plan.payload.items.forEach((x,i)=>{validatePlanItem(x,i);if(courseKey(x.objectiveRef.courseRef)!==courseKey(plan.payload.courseRef))fail('INVALID_SESSION_PLAN');total+=x.estimatedMinutes;});if(total!==plan.payload.totalEstimatedMinutes||total+plan.payload.unusedMinutes!==plan.payload.durationMinutes)fail('INVALID_SESSION_PLAN');return plan;
}
function validateRecommendationPlan(recommendation,plan){validateRecommendation(recommendation);validatePlan(plan);const item=plan.payload.items[0];if(!item||objectiveKey(item.objectiveRef)!==objectiveKey(recommendation.objectiveRef)||activityKey(item.activityRef)!==activityKey(recommendation.preferredActivityRef)||item.action!==recommendation.action||item.estimatedMinutes!==recommendation.estimatedMinutes)fail('RECOMMENDATION_PLAN_MISMATCH');return true;}
function renderToday({recommendation,plan,resumeState}){if(!recommendation||!plan)return '<section class="atlas-m1 atlas-today" aria-labelledby="atlas-today-title"><h1 id="atlas-today-title">Aujourd’hui</h1><p>Aucune séance admissible pour le moment.</p></section>';validateRecommendationPlan(recommendation,plan);const reasons=recommendation.reasonCodes.map(x=>`<li>${esc(REASON_LABELS[x])}</li>`).join('');const items=plan.payload.items.map(x=>`<li><span>${esc(x.action)}</span><strong>${x.estimatedMinutes} min</strong></li>`).join('');const resume=resumeState?'<button type="button" data-atlas-action="resume">Reprendre la séance</button>':'';return `<section class="atlas-m1 atlas-today" aria-labelledby="atlas-today-title"><h1 id="atlas-today-title">Aujourd’hui</h1><p class="atlas-duration">${plan.payload.durationMinutes} minutes · ${plan.payload.totalEstimatedMinutes} prévues</p><ul class="atlas-reasons">${reasons}</ul><ol class="atlas-plan-preview">${items}</ol><div class="atlas-actions">${resume}<button class="atlas-primary" type="button" data-atlas-action="start">Commencer</button></div></section>`;}
module.exports=Object.freeze({REASON_LABELS,ACTION_CLASS,esc,assertClosed,courseKey,objectiveKey,activityKey,validateRecommendation,validatePlan,validateRecommendationPlan,renderToday});
