'use strict';
function createSessionController({core,focus}){if(!core||typeof core.commitActivitySubmission!=='function'||typeof core.requestAssistance!=='function')throw new Error('CORE_PORT_REQUIRED');let state={sessionId:null,itemPosition:0,committed:null,help:null};return Object.freeze({
 start(sessionRef,resumeState){state={sessionId:sessionRef.sessionId,itemPosition:resumeState?.nextItemPosition||0,committed:null,help:null};if(resumeState?.focusTarget)focus?.(resumeState.focusTarget);return {...state};},
 async submit(rawResponse){const result=await core.commitActivitySubmission(state.sessionId,state.itemPosition,rawResponse);if(!result||!result.event||!result.resumeState)throw new Error('CORE_COMMIT_NOT_CONFIRMED');state.committed=result;state.itemPosition=result.resumeState.nextItemPosition;if(result.resumeState.focusTarget)focus?.(result.resumeState.focusTarget);return result;},
 async requestHelp(kind){const confirmation=await core.requestAssistance(state.sessionId,state.itemPosition,kind);if(!confirmation||confirmation.committed!==true)throw new Error('ASSISTANCE_NOT_PERSISTED');state.help=confirmation.record;return confirmation;},
 snapshot(){return structuredClone(state);}
 });}
function renderSession({plan,resumeState,activityHtml='',feedbackHtml=''}){if(!plan?.payload?.items?.length)return '<section class="atlas-m1"><h1>Aucune séance en cours</h1></section>';const pos=resumeState?.nextItemPosition||0,item=plan.payload.items[Math.min(pos,plan.payload.items.length-1)];const labels={practice:'Entraînement',correction:'Correction',validation:item.action==='maintain-recent-validation'?'Reconfirmation':'Validation'};return `<section class="atlas-m1 atlas-session" aria-labelledby="atlas-session-title"><header><p>${labels[item.executionClass]||'Activité'}</p><h1 id="atlas-session-title">Étape ${item.position+1} sur ${plan.payload.items.length}</h1></header><div class="atlas-activity" id="atlas-session-item-${item.position}">${activityHtml}</div>${feedbackHtml}<div class="atlas-actions"><button type="button" data-atlas-help="hint">Indice</button><button class="atlas-primary" type="button" data-atlas-submit>Valider la réponse</button></div></section>`;}
module.exports=Object.freeze({createSessionController,renderSession});
