#!/usr/bin/env python3
import pathlib, subprocess, textwrap, unittest
ROOT=pathlib.Path(__file__).resolve().parents[1]

BASE=r'''
const assert=require('assert'),C=require(process.argv[1]+'/src/core/atlas_clock.js'),E=require(process.argv[1]+'/src/core/atlas_events.js'),S=require(process.argv[1]+'/src/ports/atlas_storage.js');
const clock=new C.ControlledAtlasClock('2026-01-01T00:00:00.000Z'),courseRef={packageLineageId:'p',courseLineageId:'c'},objectiveRef={courseRef,objectiveId:'o'},activityRef=id=>({courseRef,activityLineageId:id}),contentRevisionRef={packageLineageId:'p',packageRevisionId:'r',packageDigest:'sha256:'+'a'.repeat(64)},claimId='atlas-claim-sha256:'+'b'.repeat(64);
const activities=new Map([['practice',{type:'qcm',answer:'A',scoringRuleId:'qcm.v1',score:x=>x==='A'}],['validation',{type:'qcm',answer:'V',scoringRuleId:'val.v1',score:x=>x==='V'}]]),registry={activity:r=>activities.get(r.activityLineageId),validateClaim:()=>true};
function plan(ref=activityRef('practice')){const payload={schemaVersion:'atlas.session-plan.v1',engineVersion:'v',courseRef,contentRevisionRef,durationMinutes:5,items:[{position:0,objectiveRef,activityRef:ref,action:ref.activityLineageId==='validation'?'attempt-validation':'start-practice',executionClass:ref.activityLineageId==='validation'?'validation':'practice',estimatedMinutes:2,...(ref.activityLineageId==='validation'?{validationBasisEventId:'atlas-event-sha256:'+'1'.repeat(64),independenceClaimId:claimId}:{})}],totalEstimatedMinutes:2,unusedMinutes:3};const h=E.hash('learnit.atlas.m1.v0.3/plan-digest',payload);return{planId:'atlas-plan-sha256:'+h,planDigest:'sha256:'+h,payload};}
function setup(){const storage=new S.InMemoryAtlasStorage(),core=new S.AtlasCoreService({storage,clock,registry}),p=plan(),req=core.prepareStartRequest(p.planDigest),session=core.startSession(req.startRequestId,p);return{storage,core,p,session};}
function life(payload,kind,ordinal,at){const sessionRef=payload.resumeStates[0].sessionRef,b={eventVersion:'atlas.learning-event.v1',kind,sessionRef,eventOrdinal:ordinal,occurredAt:at};return{...b,eventId:E.eventId(b)};}
function expectImportError(core,payload,re){assert.throws(()=>core.importState(payload),re);}
'''

class Core(unittest.TestCase):
 def run_node(self,src):
  p=subprocess.run(['node','-e',textwrap.dedent(src),str(ROOT)],capture_output=True,text=True)
  self.assertEqual(p.returncode,0,p.stderr); print(p.stdout.strip()); return p
 def test_semantic_and_fail_closed(self):
  self.run_node(BASE+r'''
let n=0;const ok=x=>{assert.ok(x);n++},bad=(f,r)=>{assert.throws(f,r);n++};bad(()=>C.assertCanonicalTimestamp('2026-01-01T00:00:00Z'),/NON_CANONICAL/);bad(()=>E.canonical({x:undefined}),/NON_CANONICAL/);const{storage,core,session}=setup(),first=core.commitActivitySubmission(session.sessionId,0,'B');ok(first.execution.outcome==='incorrect');ok(core.evidence()[0].state==='review-needed');const before=JSON.stringify(storage.snapshot());storage.injectFailure();bad(()=>core.commitActivitySubmission(session.sessionId,0,'A'),/FAULT_INJECTED/);ok(JSON.stringify(storage.snapshot())===before);core.lifecycle(session.sessionId,'session-interrupted');core.lifecycle(session.sessionId,'session-resumed');ok(core.exportState().namespace==='learnit.atlas.m1.v2');bad(()=>core.importState({atlasStateVersion:'0.2',namespace:'learnit.atlas.m1.v1'}),/UNSUPPORTED/);console.log(`ATLAS_CORE_SEMANTIC_PASS ${n}/${n}`);
''')
 def test_v3_relational_import_matrix(self):
  self.run_node(BASE+r'''
let n=0;const ok=x=>{assert.ok(x);n++},bad=(c,p,r)=>{expectImportError(c,p,r);n++};const a=setup(),base=a.core.exportState(),sid=a.session.sessionId;const valid=structuredClone(base);valid.learningEvents.push(life(valid,'session-interrupted',1,'2026-01-01T00:00:01.000Z'),life(valid,'session-resumed',2,'2026-01-01T00:00:02.000Z'),life(valid,'session-completed',3,'2026-01-01T00:00:03.000Z'));valid.resumeStates[0].lifecycleOrdinal=3;ok(new S.AtlasCoreService({storage:new S.InMemoryAtlasStorage(),clock,registry}).importState(valid));
for(const mutate of[
 p=>{p.learningEvents.push(life(p,'session-interrupted',1,'2026-01-01T00:00:01.000Z'),life(p,'session-resumed',1,'2026-01-01T00:00:02.000Z'));p.resumeStates[0].lifecycleOrdinal=2},
 p=>{p.learningEvents.push(life(p,'session-interrupted',2,'2026-01-01T00:00:01.000Z'));p.resumeStates[0].lifecycleOrdinal=1},
 p=>{p.learningEvents.push(life(p,'session-resumed',1,'2026-01-01T00:00:01.000Z'));p.resumeStates[0].lifecycleOrdinal=1},
 p=>{p.learningEvents.push(life(p,'session-interrupted',1,'2026-01-01T00:00:01.000Z'),life(p,'session-completed',2,'2026-01-01T00:00:02.000Z'));p.resumeStates[0].lifecycleOrdinal=2},
 p=>{p.learningEvents.push(life(p,'session-completed',1,'2026-01-01T00:00:01.000Z'),life(p,'session-interrupted',2,'2026-01-01T00:00:02.000Z'));p.resumeStates[0].lifecycleOrdinal=2},
 p=>{p.learningEvents.push(life(p,'session-interrupted',1,'2026-01-01T00:00:01.000Z'));p.resumeStates[0].lifecycleOrdinal=0},
]){const p=structuredClone(base);mutate(p);bad(a.core,p,/LIFECYCLE_/)}
const assisted=setup();clock.set('2026-01-01T00:00:01.000Z');const help1=assisted.core.requestAssistance(assisted.session.sessionId,0,'hint').record;clock.set('2026-01-01T00:00:02.000Z');const help2=assisted.core.requestAssistance(assisted.session.sessionId,0,'guided-step').record;clock.set('2026-01-01T00:00:03.000Z');const sub=assisted.core.commitActivitySubmission(assisted.session.sessionId,0,'A');const good=assisted.core.exportState();ok(new S.AtlasCoreService({storage:new S.InMemoryAtlasStorage(),clock,registry}).importState(good));const perm=structuredClone(good);perm.scoredExecutions[0].assistanceUseIds.reverse();perm.scoredExecutions[0].executionId=E.executionId(E.without(perm.scoredExecutions[0],'executionId'));const ev=perm.learningEvents.find(x=>x.executionId===sub.execution.executionId);ev.executionId=perm.scoredExecutions[0].executionId;ev.eventId=E.eventId(E.pedagogicalEventIdentity(ev));ok(new S.AtlasCoreService({storage:new S.InMemoryAtlasStorage(),clock,registry}).importState(perm));
for(const mutate of[
 p=>{p.scoredExecutions[0].assistance='none';p.scoredExecutions[0].assistanceUseIds=[]},
 p=>{p.scoredExecutions[0].assistanceUseIds=[help1.assistanceUseId]},
 p=>{p.scoredExecutions[0].assistanceUseIds.push('atlas-assistance-sha256:'+'f'.repeat(64))},
 p=>{p.resumeStates[0].itemStates[0].assistanceUseIds=[]},
]){const p=structuredClone(good);mutate(p);const x=p.scoredExecutions[0];x.executionId=E.executionId(E.without(x,'executionId'));const e=p.learningEvents.find(q=>q.executionId===sub.execution.executionId);e.executionId=x.executionId;e.eventId=E.eventId(E.pedagogicalEventIdentity(e));bad(assisted.core,p,/ASSISTANCE_/)}
const boundary=structuredClone(good);boundary.atlasMeta.assistanceUses[help2.assistanceUseId].recordedAt=boundary.scoredExecutions[0].submittedAt;const hr=boundary.atlasMeta.assistanceUses[help2.assistanceUseId];delete boundary.atlasMeta.assistanceUses[help2.assistanceUseId];hr.assistanceUseId=E.assistanceUseId(E.without(hr,'assistanceUseId'));boundary.atlasMeta.assistanceUses[hr.assistanceUseId]=hr;boundary.resumeStates[0].itemStates[0].assistanceUseIds=[help1.assistanceUseId,hr.assistanceUseId];boundary.scoredExecutions[0].assistanceUseIds=[help1.assistanceUseId,hr.assistanceUseId];const bx=boundary.scoredExecutions[0];bx.executionId=E.executionId(E.without(bx,'executionId'));const be=boundary.learningEvents.find(q=>q.executionId===sub.execution.executionId);be.executionId=bx.executionId;be.eventId=E.eventId(E.pedagogicalEventIdentity(be));bad(assisted.core,boundary,/ASSISTANCE_/);
const atomic=new S.InMemoryAtlasStorage(),atomicCore=new S.AtlasCoreService({storage:atomic,clock,registry}),snap=JSON.stringify(atomic.snapshot());bad(atomicCore,structuredClone(boundary),/ASSISTANCE_/);ok(JSON.stringify(atomic.snapshot())===snap);const runtime=setup();runtime.core.lifecycle(runtime.session.sessionId,'session-completed');const rb=JSON.stringify(runtime.storage.snapshot());assert.throws(()=>runtime.core.lifecycle(runtime.session.sessionId,'session-interrupted'),/LIFECYCLE_/);ok(JSON.stringify(runtime.storage.snapshot())===rb);console.log(`ATLAS_CORE_V3_RELATIONAL_PASS ${n}/${n}`);
''')
 def test_indexeddb_atomic_reopen(self):
  self.run_node(r'''
const assert=require('assert'),C=require(process.argv[1]+'/src/core/atlas_clock.js'),E=require(process.argv[1]+'/src/core/atlas_events.js'),I=require(process.argv[1]+'/src/adapters/atlas_indexeddb.js');
function req(result){const r={result,error:null,onsuccess:null,onerror:null};queueMicrotask(()=>r.onsuccess&&r.onsuccess());return r}function fake(){const dbs=new Map(),transactions=[];function conn(d){return{objectStoreNames:{contains:n=>d.k.has(n)},createObjectStore(n,o){d.k.set(n,o.keyPath);d.s.set(n,new Map())},transaction(names,mode){names=Array.isArray(names)?names:[names];transactions.push({names:[...names],mode});const w=new Map(names.map(n=>[n,new Map([...d.s.get(n)].map(([k,v])=>[k,structuredClone(v)]))]));let aborted=false;const t={error:null,oncomplete:null,onabort:null,onerror:null,objectStore(n){const key=v=>d.k.get(n).split('.').reduce((x,p)=>x[p],v);return{clear(){w.get(n).clear();return req()},put(v){w.get(n).set(key(v),structuredClone(v));return req()},getAll(){return req([...w.get(n).values()].map(v=>structuredClone(v)))},get(k){return req(w.get(n).has(k)?structuredClone(w.get(n).get(k)):undefined)}}},abort(){aborted=true;t.error=new Error('AbortError');queueMicrotask(()=>t.onabort&&t.onabort())}};setTimeout(()=>{if(aborted)return;if(mode==='readwrite')for(const n of names)d.s.set(n,w.get(n));t.oncomplete&&t.oncomplete()},0);return t},close(){}}}return{transactions,open(name,version){const r={result:null,error:null,onupgradeneeded:null,onsuccess:null,onerror:null};queueMicrotask(()=>{let d=dbs.get(name),up=!d;if(!d){d={k:new Map(),s:new Map()};dbs.set(name,d)}r.result=conn(d);if(up&&r.onupgradeneeded)r.onupgradeneeded();r.onsuccess&&r.onsuccess()});return r}}}
(async()=>{let n=0;const f=fake(),clock=new C.ControlledAtlasClock('2026-01-01T00:00:00.000Z'),courseRef={packageLineageId:'p',courseLineageId:'c'},objectiveRef={courseRef,objectiveId:'o'},contentRevisionRef={packageLineageId:'p',packageRevisionId:'r',packageDigest:'sha256:'+'a'.repeat(64)},activityRef={courseRef,activityLineageId:'practice'},registry={activity:()=>({type:'qcm',answer:'A',scoringRuleId:'qcm.v1',score:x=>x==='A'})},payload={schemaVersion:'atlas.session-plan.v1',engineVersion:'v',courseRef,contentRevisionRef,durationMinutes:5,items:[{position:0,objectiveRef,activityRef,action:'start-practice',executionClass:'practice',estimatedMinutes:2}],totalEstimatedMinutes:2,unusedMinutes:3};const h=E.hash('learnit.atlas.m1.v0.3/plan-digest',payload),plan={planId:'atlas-plan-sha256:'+h,planDigest:'sha256:'+h,payload},s=await I.IndexedDbAtlasStorage.open(f),core=new I.IndexedDbAtlasCoreService({storage:s,clock,registry}),rq=await core.prepareStartRequest(plan.planDigest),session=await core.startSession(rq.startRequestId,plan),txStart=f.transactions.length;await core.commitActivitySubmission(session.sessionId,0,'B');assert.deepStrictEqual(f.transactions.slice(txStart).filter(x=>x.mode==='readwrite'),[{names:['scoredExecutions','learningEvents','resumeStates'],mode:'readwrite'}]);n++;const before=s.snapshot();s.injectAbortAfterStore('scoredExecutions');await assert.rejects(core.commitActivitySubmission(session.sessionId,0,'A'));assert.deepStrictEqual(s.snapshot(),before);n++;s.close();const r=await I.IndexedDbAtlasStorage.open(f);assert.deepStrictEqual(r.snapshot(),before);n++;const bad=core.exportState();bad.resumeStates[0].lifecycleOrdinal=1;const rb=r.snapshot(),rc=new I.IndexedDbAtlasCoreService({storage:r,clock,registry});await assert.rejects(rc.importState(bad),/LIFECYCLE_/);assert.deepStrictEqual(r.snapshot(),rb);n++;r.close();const rr=await I.IndexedDbAtlasStorage.open(f);assert.deepStrictEqual(rr.snapshot(),rb);n++;console.log(`ATLAS_CORE_INDEXEDDB_PASS ${n}/${n}`)})().catch(e=>{console.error(e);process.exit(1)});
''')
 def test_forbidden_dependencies(self):
  text='\n'.join(p.read_text() for p in ROOT.rglob('atlas_*.js'))
  for x in ('fetch(','WebSocket','XMLHttpRequest','Math.random','learnit_atlas_m1_v1'): self.assertNotIn(x,text)
if __name__=='__main__': unittest.main(verbosity=2)
